package year2018.day2

class DayTwoInput {

    private static String input = "krdmtuqjmwfoevnadixyclzspv\n" +
            "yrdmtuqjiwfoevnabfxyclzsph\n" +
            "kqjvtuqjgwfoevnabixyclzsph\n" +
            "krdmtuqjgwjoevnaolxyclzsph\n" +
            "krdmtnqjgwfoevnabiiyxlzsph\n" +
            "lrymtuqjgwhoevnabixyclzsph\n" +
            "krdmguqjgwfoevnabixkclzsah\n" +
            "krdmtuqjgwfoevnibinyclzdph\n" +
            "krdmtucjgwfoevnabhxyclzspv\n" +
            "krdmtuqjgwfoevtabixyulzsuh\n" +
            "krdmtuqqgwfoevnabixdblzsph\n" +
            "krdmtuqjawfsevnabiyyclzsph\n" +
            "krdmtuqjgwfoevnabzxccldsph\n" +
            "krdmtcqegwfhevnabixyclzsph\n" +
            "krdmtuqjgwforvnaxixycgzsph\n" +
            "krdmtuqjgwfoqvnaxixyclzskh\n" +
            "krdmtutjgwfoevyajixyclzsph\n" +
            "krdmtuqmgwfoevnabixycxzspc\n" +
            "krdptuqjgwhoevkabixyclzsph\n" +
            "krdttuqjhwfoevnabixyclzspa\n" +
            "krdmtuqjgwfoevnabibyhnzsph\n" +
            "krdmtuqjywfoevntbidyclzsph\n" +
            "krdmtojdgwfoevnabixyclzsph\n" +
            "krdmtuqjgpfuevnauixyclzsph\n" +
            "krdmtoqjgwfrevjabixyclzsph\n" +
            "krdmtuqjgwfoyvndbixyclzyph\n" +
            "krdmtxqjgwfomvnayixyclzsph\n" +
            "crdmtuqjgwfoevnabixyoxzsph\n" +
            "krdmtpqjgwfdevnabixycqzsph\n" +
            "krdmtuqjgwfoevuabfxsclzsph\n" +
            "krdmtuqjgwfoevnybixycdzskh\n" +
            "krdmtusjgwfoevnabixxclzdph\n" +
            "krdmtuqjgwfoevnaboxyglzjph\n" +
            "zrdmtuqjgrfoevnalixyclzsph\n" +
            "krdmtuqjclfoevnabixyclzsih\n" +
            "kqdmtlqjgwfoevnabtxyclzsph\n" +
            "krdmtuqggwpoevnabixyclzlph\n" +
            "krdmtuqjgwfobwnrbixyclzsph\n" +
            "krdmtuqjgwfoevwabkxycnzsph\n" +
            "kldmtuqjgwfogvyabixyclzsph\n" +
            "krdmtuqvgwfoevnabixtcrzsph\n" +
            "krdmtuqjgwroevnabixyrlzspw\n" +
            "krdmtuqjgjfoevnabixyelzrph\n" +
            "krdmtuqjgffoevnaaixyclzspa\n" +
            "krdmtuqjgwfoevxabifywlzsph\n" +
            "krdmtuqjgwfoevlabixycrzsrh\n" +
            "krdmtuqjgwfpevnabixocqzsph\n" +
            "krdmtuqjgwfoevdabixycnhsph\n" +
            "krdmtmqjgwfoevnajixyclvsph\n" +
            "krdmtuqjjvfoevnabgxyclzsph\n" +
            "krzmtuqjgwfoevnabioyckzsph\n" +
            "kodmtwqjgwfoevnabieyclzsph\n" +
            "ehdmthqjgwfoevnabixyclzsph\n" +
            "krdmtuqjxwioevnabixyclbsph\n" +
            "grdmkutjgwfoevnabixyclzsph\n" +
            "krdutuqjgwfoebnabixaclzsph\n" +
            "krdmtuqjgwfoebnabixyclcjph\n" +
            "krdmteqjgwfoevnlbixycizsph\n" +
            "krdmtegjgwhoevnabixyclzsph\n" +
            "krdmtuqjgwfdrvnabixbclzsph\n" +
            "krdmtuqjgyfoevidbixyclzsph\n" +
            "krdmtubjawfoevnabixyclzuph\n" +
            "krdmtuqjgwfoavjabixyclzssh\n" +
            "krdmtuqjgwfoeonabixyclzsvo\n" +
            "vrdmtuqjgwffevnabixpclzsph\n" +
            "krdmtuqonwfoevnabixycfzsph\n" +
            "krdmtumjgwfpevnubixyclzsph\n" +
            "krdmtutjgwfoevnaciyyclzsph\n" +
            "krdrtuqjgwfoevnwbixyglzsph\n" +
            "krdmtuqjgwfoevbabixyclesdh\n" +
            "krdmtuqcgwfoevnabixyqdzsph\n" +
            "krdmtuqjgwfogvnabrxycezsph\n" +
            "krdmujqkgwfoevnabixyclzsph\n" +
            "krdmtuqjgtooevnabixyclzzph\n" +
            "jrdntuqjgwfoevnabixyclrsph\n" +
            "krdmtuqjgzfoevkebixyclzsph\n" +
            "krdmtuqjgwfosvnaeixyclztph\n" +
            "krdmtuqjgwfoevzabixydlzaph\n" +
            "krdmtuqzgwfoavnabiqyclzsph\n" +
            "krdmtuqvgwfoevnabixycwzspv\n" +
            "krdmvuqjgwteevnabixyclzsph\n" +
            "krdmtujjgwfoevgybixyclzsph\n" +
            "kydmtuqjgwfoeunacixyclzsph\n" +
            "krdmtuqjgifoqvnabicyclzsph\n" +
            "krnltiqjgwfoevnabixyclzsph\n" +
            "krdmtuqjgwfoevnabhxyclzsgi\n" +
            "kfdmtuqjnwfowvnabixyclzsph\n" +
            "kmdmtuljgwfoevnabixycvzsph\n" +
            "krdmtxqjgwaoevvabixyclzsph\n" +
            "kramduqjgwfoevnabixyclzwph\n" +
            "krdutuqjgwfoennabixyclziph\n" +
            "krdmvuqfgwfoevnacixyclzsph\n" +
            "krdmtuqogwfoevnabmvyclzsph\n" +
            "krdmfuqjgwfoyvnabixyclzseh\n" +
            "krdmtuqjgweoelnabixyclzspd\n" +
            "krdmtumjgwfoevnabixyclzypo\n" +
            "krdmtuqjgkfoevhabixyclzsqh\n" +
            "kjdmtuqjgwfoevgabixyclzsah\n" +
            "krdmtuqjgwfoevnlbixyclzsbw\n" +
            "mrdmtxqjgwfoevnabgxyclzsph\n" +
            "krdmtuqpgwfoevnhbixycltsph\n" +
            "krdmtuqjgwfmqvnabixyclzslh\n" +
            "krqmtuqogwfoevnaqixyclzsph\n" +
            "krdmtusjggfoevnabicyclzsph\n" +
            "krcmtuljgwfoevlabixyclzsph\n" +
            "krdmtuojgwfoeknabixyclzsrh\n" +
            "krdmtuqjtwfoevnabiypclzsph\n" +
            "krvmtupjgwfoevnabixycldsph\n" +
            "krdmtuxjgwfoevaabxxyclzsph\n" +
            "krdmtvqlgwfoehnabixyclzsph\n" +
            "wrdmtuqjgwfoevnabixyclzdpy\n" +
            "krdatuqlgwfoevnabixyclzsjh\n" +
            "krdmtuqjgwfoevpabkxyclzsjh\n" +
            "krdmtuqjgwqvsvnabixyclzsph\n" +
            "krdmtwqjgwfoevnobixyclzspm\n" +
            "krdmtuqjgssoevnabixyclgsph\n" +
            "krdmtuqjgwfoevnafixyclzbpp\n" +
            "krdmtuqjowfoevxabiuyclzsph\n" +
            "krdmtuqrgwfoevntbixyclzspu\n" +
            "krdmtucjgwfoevnabixcnlzsph\n" +
            "krddtuojgwfoevnabixyclzzph\n" +
            "krdmtuqjgwuoevnabiqycldsph\n" +
            "kpdmpuqjgwfoevnabixyclzslh\n" +
            "krdmtuqjgwfoewnabixyzxzsph\n" +
            "krdmtuejswfoevhabixyclzsph\n" +
            "krdmtuqggwfoevntbikyclzsph\n" +
            "krdmtuqjgwfoevnabixydlhnph\n" +
            "krdmtcqjglfoevnaxixyclzsph\n" +
            "krumyuqjgwfoevnrbixyclzsph\n" +
            "kgdmmuqjgwooevnabixyclzsph\n" +
            "krdmteqjgwfqevwabixyclzsph\n" +
            "krdmfuqjgwfpevnabixyclzspq\n" +
            "erdmtycjgwfoevnabixyclzsph\n" +
            "krdmcuqjgwfoevnabixjglzsph\n" +
            "krdmtuqjgtfoeunabixiclzsph\n" +
            "krdmtuqjgwfoevmqbixyclzspu\n" +
            "krlmtuqjvwfoevnabikyclzsph\n" +
            "krdotuqjgwfoevnagrxyclzsph\n" +
            "krdmtuqbgwfoefnabixyclasph\n" +
            "kwdmtuqjgwfosjnabixyclzsph\n" +
            "kydmtuqjgwfoevcabixycezsph\n" +
            "crdmtuqjgwloevnabixkclzsph\n" +
            "krimtuqhgwfoevnbbixyclzsph\n" +
            "krdmjuqagwfoevnabicyclzsph\n" +
            "krdmtuqdgzfoevnabixydlzsph\n" +
            "krdmtuqjgwwoevnaqixyclzspf\n" +
            "krdmtuqjgwfoevnabdxyzvzsph\n" +
            "krdmtuqjgwaofvnabixyclzsnh\n" +
            "krdmturjgwfmevnabixyclzspn\n" +
            "krdmvuqjgwboevnabixyolzsph\n" +
            "krdmtuqjgwfomvnabijyclzspx\n" +
            "bedmtuqjgwfoevnabixyslzsph\n" +
            "krdmtenjgwfoevnabixyclzsqh\n" +
            "krdmtuqugwfoevnabixpcdzsph\n" +
            "krdmtuqjgiloevnabrxyclzsph\n" +
            "krdmtupjcwfoevnabixyclwsph\n" +
            "kremtuqjgwfoevnabixyyjzsph\n" +
            "krdmtuqjgwnoovnabixyclzshh\n" +
            "qrdmtuqjgwfoevnabixyciasph\n" +
            "krdituqjgbfoevnagixyclzsph\n" +
            "krdmnoqjgwfoqvnabixyclzsph\n" +
            "krdmtuqegwfoevhkbixyclzsph\n" +
            "krdmkucjgwfoevnabixnclzsph\n" +
            "krdmtuqbnwpoevnabixyclzsph\n" +
            "krdmttqjgwfoevnabixyclbspz\n" +
            "srdmtubjgwfrevnabixyclzsph\n" +
            "krdmruqjzwfoevnabixyclesph\n" +
            "ardmtuqfgwwoevnabixyclzsph\n" +
            "yrumtuqjgwhoevnabixyclzsph\n" +
            "rrdmtuqjgwfoevnabsxycwzsph\n" +
            "krpmtuqjgwfoevdabixyclzzph\n" +
            "krdmuuqjgwfoevnabixyclriph\n" +
            "krdmtuqjgwfobvnabixyvgzsph\n" +
            "krdmbuujgwfoevnabixycczsph\n" +
            "krhmtuwjgwfoeqnabixyclzsph\n" +
            "krdwtuqjgwfoevnkbixyclzzph\n" +
            "krdmtuqjgwkoeqnabixyvlzsph\n" +
            "kadmtuqjgwfoednabcxyclzsph\n" +
            "krdmtyqqgwfoevnabizyclzsph\n" +
            "krdmtuqjgnfoevnabiyycmzsph\n" +
            "krdmtuqjcwfouvnabixyclznph\n" +
            "krdmtuqjjwfcevnqbixyclzsph\n" +
            "krdmtuqfgbfoevgabixyclzsph\n" +
            "kkdmtuqjgwfoevnapixyclzsth\n" +
            "nrdmtuqjgwtoevnakixyclzsph\n" +
            "krdmtuqjglfoevlabixdclzsph\n" +
            "zrdmtuqjgwfoevndbixbclzsph\n" +
            "krdmeuqjgwfoeenabixyclrsph\n" +
            "krdmoaqjzwfoevnabixyclzsph\n" +
            "krsmtuqjgwfoevnwbixyclzsfh\n" +
            "kadmtuqjgwfoqdnabixyclzsph\n" +
            "krsmtuqjgofoevnabixkclzsph\n" +
            "krdmtuqjdwfoevnibixdclzsph\n" +
            "mrdmtuqjgwfouvnabixyclzfph\n" +
            "trdmtlqjgwfoevnabixyclzjph\n" +
            "trdmyuqjgwfozvnabixyclzsph\n" +
            "krdmtiqjgwroevnabixyclzspk\n" +
            "erdmtutjgwftevnabixyclzsph\n" +
            "krdwyuqjgwfoevnaaixyclzsph\n" +
            "krdmthqbgwfoevnabixyclksph\n" +
            "krdmttqjgwfoivnabixyclvsph\n" +
            "krdmtuqjgwfoefnabixyflgsph\n" +
            "khdmtuqjgwfoevnajixyvlzsph\n" +
            "krdmtuqvgwfoevnasixyclzspt\n" +
            "krdmtuqjgkwogvnabixyclzsph\n" +
            "krdmtuqjgwfoevnaboxpglzjph\n" +
            "kadmtuqjgwfoxvnabixyclziph\n" +
            "krdmtuqjfwfoevnabaxycbzsph\n" +
            "krdjtuqjgwfoevnabiryhlzsph\n" +
            "krdvtuqjgpfoevnabcxyclzsph\n" +
            "brdmtuqjgwfoevnafixyqlzsph\n" +
            "krdmtuqjgwfoevnavixxcllsph\n" +
            "krdhtuqjkwfoevfabixyclzsph\n" +
            "krdmtuqjgjfoevnawixyclzsuh\n" +
            "krddtuqjgwfoeqnabiwyclzsph\n" +
            "krhmtuqjgwfnevnabinyclzsph\n" +
            "kedmtuqjgzfmevnabixyclzsph\n" +
            "qrdmtuqjgwfoevntbixyclzxph\n" +
            "krdmtuqsgwfoevnabixvclzrph\n" +
            "scdmtuqjgwfoevnabixtclzsph\n" +
            "krymtuqjgjfolvnabixyclzsph\n" +
            "krdmtuqjgwfkevnablxyclzskh\n" +
            "krymtuqjswfoevnabixyclzvph\n" +
            "krdmtuqjhwfoevnabixycwzspd\n" +
            "krdmtuxjgwfoevnabyxyclzzph\n" +
            "krdmtlqjgwfovvnabilyclzsph\n" +
            "krdmtuqjgwfoevnaaijcclzsph\n" +
            "krdatrqjgwfokvnabixyclzsph\n" +
            "krdmtuqjgwfoevnaxifyclzkph\n" +
            "krddtuqjgwfoevnabixccozsph\n" +
            "krdmtuqngwfoevnabiyycxzsph\n" +
            "krdmtumdgwfoevnqbixyclzsph\n" +
            "krdmtuqjgwfoevnabixyxlmsch\n" +
            "krdmtudzgwfoevnabixtclzsph\n" +
            "krdmtuqjgwfoevnpbixyclhspl\n" +
            "krdmtqqjgwjoevnabexyclzsph\n" +
            "kydmtuqzgwfoevnabixyclwsph\n" +
            "krdmeucjgwqoevnabixyclzsph\n" +
            "krdmtuqjghfoevjabixyclzspp\n" +
            "krdmtuqjgjfwevnabixyclzskh\n" +
            "krdmkuhjgwfoevnabipyclzsph\n" +
            "krdytuqjgwfoevnabibyclztph\n" +
            "krdmtuqjgwfpevnabisyzlzsph\n" +
            "kmdmtgqjgwfsevnabixyclzsph\n" +
            "krdmtuqjgsfoevnabijyclzszh\n" +
            "krdmtuqjgwfoevnabivyclzuuh\n" +
            "krdstuqjgrfoevnabixyclzspu\n" +
            "jrdmtuqjgwfotvnabixyclzspj\n" +
            "krdmrumjgwfoevnabixeclzsph\n" +
            "krpmtusjgwfoevnabioyclzsph\n"
}
